/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Button.h"
#include "Button_aliases.h"
#include "LED_G.h"
#include "LED_G_aliases.h"
#include "LED_R.h"
#include "LED_R_aliases.h"
#include "LED_B.h"
#include "LED_B_aliases.h"
#include "SW_Tx_UART.h"
#include "SW_Tx_UART_PVT.h"
#include "C_1.h"
#include "C_1_aliases.h"
#include "C_3.h"
#include "C_3_aliases.h"
#include "C_2.h"
#include "C_2_aliases.h"
#include "R_1.h"
#include "R_1_aliases.h"
#include "R_2.h"
#include "R_2_aliases.h"
#include "R_3.h"
#include "R_3_aliases.h"
#include "R_4.h"
#include "R_4_aliases.h"
#include "Pin_Latch.h"
#include "Pin_Latch_aliases.h"
#include "Pin_CLK.h"
#include "Pin_CLK_aliases.h"
#include "Pin_DO.h"
#include "Pin_DO_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

